<?php
declare(strict_types=1);

const APP_TIMEZONE = 'Asia/Bangkok';

// Role keys
const ROLE_ADMIN = 'ADMIN';
const ROLE_REGISTRY = 'REGISTRY';
const ROLE_VEHICLE = 'VEHICLE';
const ROLE_LEAVE = 'LEAVE';
const ROLE_FACILITY = 'FACILITY';
const ROLE_GENERAL = 'GENERAL';

// Circulars
const CIRCULAR_TYPE_INTERNAL = 'INTERNAL';
const CIRCULAR_TYPE_EXTERNAL = 'EXTERNAL';

const CIRCULAR_STATUS_DRAFT = 'DRAFT';
const CIRCULAR_STATUS_SENT = 'SENT';
const CIRCULAR_STATUS_RECALLED = 'RECALLED';
const CIRCULAR_STATUS_RETURNED = 'RETURNED';
const CIRCULAR_STATUS_FORWARDED = 'FORWARDED';
const CIRCULAR_STATUS_APPROVED = 'APPROVED';
const CIRCULAR_STATUS_ARCHIVED = 'ARCHIVED';
const CIRCULAR_STATUS_CANCELLED = 'CANCELLED';

const INBOX_TYPE_NORMAL = 'NORMAL';
const INBOX_TYPE_DIRECTOR = 'DIRECTOR_BOX';
const INBOX_TYPE_CLERK = 'CLERK_BOX';
const INBOX_TYPE_CLERK_RETURN = 'CLERK_RETURN_BOX';

// Outgoing letters
const OUTGOING_STATUS_WAITING_ATTACHMENT = 'WAITING_ATTACHMENT';
const OUTGOING_STATUS_COMPLETE = 'COMPLETE';

// Government orders
const ORDER_STATUS_WAITING_ATTACHMENT = 'WAITING_ATTACHMENT';
const ORDER_STATUS_COMPLETE = 'COMPLETE';
const ORDER_STATUS_SENT = 'SENT';
