<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "This script must be run from CLI.\n");
    exit(1);
}

$_SERVER['REQUEST_METHOD'] = 'CLI';
$_SERVER['REQUEST_URI'] = 'cli://scripts/import-legacy-signatures.php';
$_SERVER['SERVER_NAME'] = 'codex-cli';

require_once __DIR__ . '/../config/connection.php';
require_once __DIR__ . '/../app/modules/audit/logger.php';

/**
 * @return array<int, array<string, string>>
 */
function load_signature_import_rows(string $csv_path): array
{
    if (!is_file($csv_path)) {
        throw new RuntimeException('Signature import map not found: ' . $csv_path);
    }

    $handle = fopen($csv_path, 'rb');

    if ($handle === false) {
        throw new RuntimeException('Unable to open CSV: ' . $csv_path);
    }

    $header = fgetcsv($handle, 0, ',', '"', '\\');

    if (!is_array($header)) {
        fclose($handle);
        throw new RuntimeException('CSV header missing: ' . $csv_path);
    }

    $header = array_map(static function ($value): string {
        $value = (string) $value;

        if (str_starts_with($value, "\xEF\xBB\xBF")) {
            $value = substr($value, 3);
        }

        return trim($value);
    }, $header);

    $rows = [];

    while (($data = fgetcsv($handle, 0, ',', '"', '\\')) !== false) {
        if ($data === [null] || $data === []) {
            continue;
        }

        $row = [];

        foreach ($header as $index => $column) {
            $row[$column] = trim((string) ($data[$index] ?? ''));
        }

        $rows[] = $row;
    }

    fclose($handle);

    return $rows;
}

/**
 * @param list<string> $pids
 * @return array<string, string>
 */
function load_current_signatures(mysqli $connection, array $pids): array
{
    if ($pids === []) {
        return [];
    }

    $placeholders = implode(', ', array_fill(0, count($pids), '?'));
    $types = str_repeat('s', count($pids));
    $sql = 'SELECT pID, COALESCE(signature, "") AS signature FROM teacher WHERE pID IN (' . $placeholders . ')';
    $stmt = mysqli_prepare($connection, $sql);

    if ($stmt === false) {
        throw new RuntimeException('Prepare failed: ' . mysqli_error($connection));
    }

    mysqli_stmt_bind_param($stmt, $types, ...$pids);
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);
    $signatures = [];

    while ($row = mysqli_fetch_assoc($result)) {
        $signatures[(string) ($row['pID'] ?? '')] = (string) ($row['signature'] ?? '');
    }

    mysqli_stmt_close($stmt);

    return $signatures;
}

/**
 * @param list<array<string, string>> $rows
 */
function write_restore_sql(string $path, array $rows): void
{
    $dir = dirname($path);

    if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
        throw new RuntimeException('Unable to create backup directory: ' . $dir);
    }

    $lines = [
        '-- Restore teacher.signature values generated by import-legacy-signatures.php',
        '-- Generated at ' . date('c'),
        '',
    ];

    foreach ($rows as $row) {
        $pid = str_replace("'", "''", (string) ($row['pID'] ?? ''));
        $previous = (string) ($row['previous_signature'] ?? '');

        if ($previous === '') {
            $lines[] = "UPDATE teacher SET signature = NULL WHERE pID = '{$pid}';";
            continue;
        }

        $signature = str_replace("'", "''", $previous);
        $lines[] = "UPDATE teacher SET signature = '{$signature}' WHERE pID = '{$pid}';";
    }

    file_put_contents($path, implode(PHP_EOL, $lines) . PHP_EOL);
}

/**
 * @param list<array<string, string>> $rows
 */
function write_report_csv(string $path, array $rows): void
{
    $dir = dirname($path);

    if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
        throw new RuntimeException('Unable to create report directory: ' . $dir);
    }

    $handle = fopen($path, 'wb');

    if ($handle === false) {
        throw new RuntimeException('Unable to open report file: ' . $path);
    }

    fwrite($handle, "\xEF\xBB\xBF");
    fputcsv($handle, [
        'legacy_id',
        'pID',
        'legacy_name',
        'source_png',
        'target_signature_path',
        'previous_signature',
        'result',
        'message',
    ], ',', '"', '\\');

    foreach ($rows as $row) {
        fputcsv($handle, [
            $row['legacy_id'] ?? '',
            $row['pID'] ?? '',
            $row['legacy_name'] ?? '',
            $row['png_by_id'] ?? '',
            $row['target_signature_relative_path'] ?? '',
            $row['previous_signature'] ?? '',
            $row['result'] ?? '',
            $row['message'] ?? '',
        ], ',', '"', '\\');
    }

    fclose($handle);
}

$repo_root = realpath(__DIR__ . '/..');
$default_csv = $repo_root . '/tmp/signature-import/signature_import_map.csv';
$apply = in_array('--apply', $argv, true);
$csv_path = $default_csv;

foreach (array_slice($argv, 1) as $argument) {
    if ($argument === '--apply') {
        continue;
    }

    $csv_path = str_starts_with($argument, '/') ? $argument : $repo_root . '/' . ltrim($argument, '/');
}

try {
    $rows = load_signature_import_rows($csv_path);
    $eligible_rows = [];

    foreach ($rows as $row) {
        if (($row['current_teacher_exists'] ?? '') !== '1') {
            continue;
        }

        if (($row['pID'] ?? '') === '' || ($row['png_by_id'] ?? '') === '' || ($row['target_signature_relative_path'] ?? '') === '') {
            continue;
        }

        $eligible_rows[] = $row;
    }

    $pids = array_values(array_unique(array_map(static fn(array $row): string => (string) $row['pID'], $eligible_rows)));
    $current_signatures = load_current_signatures($connection, $pids);
    $timestamp = date('Ymd_His');
    $backup_dir = $repo_root . '/tmp/signature-import/applied/' . $timestamp;
    $restore_sql_path = $backup_dir . '/restore_teacher_signature.sql';
    $report_csv_path = $backup_dir . '/signature_import_report.csv';
    $summary_json_path = $backup_dir . '/summary.json';
    $report_rows = [];
    $updated_count = 0;
    $copied_count = 0;
    $skipped_count = 0;
    $failed_count = 0;

    foreach ($eligible_rows as $row) {
        $pid = (string) $row['pID'];
        $legacy_id = (string) ($row['legacy_id'] ?? '');
        $legacy_name = (string) ($row['legacy_name'] ?? '');
        $previous_signature = (string) ($current_signatures[$pid] ?? '');
        $source_relative = (string) $row['png_by_id'];
        $target_relative = (string) $row['target_signature_relative_path'];
        $source_path = $repo_root . '/' . ltrim($source_relative, '/');
        $target_path = $repo_root . '/' . ltrim($target_relative, '/');
        $report_row = [
            'legacy_id' => $legacy_id,
            'pID' => $pid,
            'legacy_name' => $legacy_name,
            'png_by_id' => $source_relative,
            'target_signature_relative_path' => $target_relative,
            'previous_signature' => $previous_signature,
            'result' => 'SKIPPED',
            'message' => '',
        ];

        try {
            if (!is_file($source_path)) {
                throw new RuntimeException('Source png not found');
            }

            if (!$apply) {
                $report_row['result'] = 'DRY_RUN';
                $report_row['message'] = 'Ready to import';
                $report_rows[] = $report_row;
                continue;
            }

            $target_dir = dirname($target_path);

            if (!is_dir($target_dir) && !mkdir($target_dir, 0755, true) && !is_dir($target_dir)) {
                throw new RuntimeException('Unable to create target directory');
            }

            if (!copy($source_path, $target_path)) {
                throw new RuntimeException('Unable to copy signature file');
            }

            @chmod($target_path, 0644);
            $copied_count++;

            $stmt = mysqli_prepare($connection, 'UPDATE teacher SET signature = ? WHERE pID = ?');

            if ($stmt === false) {
                throw new RuntimeException('Prepare update failed: ' . mysqli_error($connection));
            }

            mysqli_stmt_bind_param($stmt, 'ss', $target_relative, $pid);
            mysqli_stmt_execute($stmt);
            $affected = mysqli_stmt_affected_rows($stmt);
            mysqli_stmt_close($stmt);

            if ($affected < 0) {
                throw new RuntimeException('Update failed');
            }

            $updated_count++;
            $report_row['result'] = 'UPDATED';
            $report_row['message'] = 'Imported successfully';
        } catch (Throwable $exception) {
            $failed_count++;
            $report_row['result'] = 'FAILED';
            $report_row['message'] = $exception->getMessage();
        }

        $report_rows[] = $report_row;
    }

    foreach ($report_rows as $report_row) {
        if (($report_row['result'] ?? '') === 'SKIPPED') {
            $skipped_count++;
        }
    }

    if ($apply) {
        write_restore_sql($restore_sql_path, $report_rows);
    }
    write_report_csv($report_csv_path, $report_rows);

    $summary = [
        'generated_at' => date('c'),
        'apply_mode' => $apply,
        'csv_path' => $csv_path,
        'eligible_rows' => count($eligible_rows),
        'copied_count' => $copied_count,
        'updated_count' => $updated_count,
        'skipped_count' => $skipped_count,
        'failed_count' => $failed_count,
        'restore_sql_path' => $apply ? $restore_sql_path : null,
        'report_csv_path' => $report_csv_path,
    ];

    $summary_dir = dirname($summary_json_path);

    if (!is_dir($summary_dir) && !mkdir($summary_dir, 0755, true) && !is_dir($summary_dir)) {
        throw new RuntimeException('Unable to create summary directory: ' . $summary_dir);
    }

    file_put_contents($summary_json_path, json_encode($summary, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . PHP_EOL);

    if (function_exists('audit_log')) {
        audit_log(
            'profile',
            'SIGNATURE_BULK_IMPORT',
            $failed_count > 0 ? 'FAIL' : 'SUCCESS',
            'teacher',
            null,
            $failed_count > 0 ? 'legacy_signature_import_partial' : 'legacy_signature_import_complete',
            [
                'eligible_rows' => count($eligible_rows),
                'copied_count' => $copied_count,
                'updated_count' => $updated_count,
                'failed_count' => $failed_count,
                'report_csv_path' => str_replace($repo_root . '/', '', $report_csv_path),
                'restore_sql_path' => $apply ? str_replace($repo_root . '/', '', $restore_sql_path) : null,
            ],
            'CLI',
            $failed_count > 0 ? 500 : 200
        );
    }

    fwrite(STDOUT, json_encode($summary, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . PHP_EOL);

    exit($failed_count > 0 ? 1 : 0);
} catch (Throwable $exception) {
    if (function_exists('audit_log')) {
        audit_log(
            'profile',
            'SIGNATURE_BULK_IMPORT',
            'FAIL',
            'teacher',
            null,
            $exception->getMessage(),
            [
                'csv_path' => $csv_path,
                'apply_mode' => $apply,
            ],
            'CLI',
            500
        );
    }

    fwrite(STDERR, $exception->getMessage() . PHP_EOL);
    exit(1);
}
